[project]
name = "vipyr-deobf"
version = "0.4.0"
description = "Rewrapping FieryIceStickie's Deobfuscation Tools"
readme = "README.md"
authors = [
    { name = "Bradley Reynolds", email = "bradley.reynolds@darbia.dev" },
]
license = { text = "MIT" }
# requires-python = ">=3.12,<3.13"
# dependencies = []

[project.urls]
repository = "https://github.com/vipyrsec/vipyrsec-deobfuscator/"

[project.scripts]
vipyr-deobf = "vipyr_deobf.cli:run"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
