name: "Publish Python 🐍 distributions 📦 to PyPI"

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

jobs:
  build:
    name: "Build publish Python 🐍 distributions"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: "Set up Python 3.x"
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: "Install pypa/build"
        run: >-
          python -m
          pip install
          build
          --user

      - name: "Build a binary wheel and a source tarball"
        run: >-
          python -m
          build
          --outdir dist/

      - name: "Upload packages"
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: packages
          path: dist

  publish:
    name: "Publish 📦 to PyPI"
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: packages

      - name: "Publish distribution 📦 to PyPI"
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # v1.8.11
        with:
          skip-existing: true
          verbose: true
          print-hash: true
